### ISSUE TITLE
OMMR4all vs. OCR4all?

### ISSUE THREAD

**Issue by wrznr** [OMMR4all/ommr4all-page-segmentation#2]
I am confused: The github repo is called `ommr4all-page-segmentation` but the documentation is for a software called `OCR4All Pixel Classifier`. How do they relate?

**Comment by kba** [comment]
Relationship with https://github.com/ocr-d-modul-2-segmentierung/ocrd-pixelclassifier-segmentation would also be interesting.

**Comment by Gawajn** [comment]
The project was originally used for layout analysis tasks/projects. (one of them is OCR4all). Since the output of the CNN depends on the training material, it can also be used for other purposes. In the Ommr4all project we use it, for example, to segment staves and symbols.

I can not say anything specific to the OCRD project. But the original repo of the project is located at https://gitlab2.informatik.uni-wuerzburg.de/ls6/ocr4all-pixel-classifier
